class cmdHelpCommand extends Command
	init: ->
		@command='/cmdhelp'
		@parseType='startsWith'
		@rankPrivelege='user'

	functionality: ->
		msg = @msgData.message
		resp = ''
		if msg.length > 9 #includes param
			param = msg.substring 9 #just param
			switch param
				when "hugs pup"
					resp = "You give me a hug!"
				when "rapes pup"
					resp = "er... thats... not a command... please"
				when "taco"
					resp = "order a yummy taco.  simply say 'taco' or give on to someone else by saying 'taco @user'"
				when "cookie"
					resp = "Mod only command.  Reward a user with a sweet treat!  Syntax: cookie @user"
				when "punish"
					resp = "Mod only command.  Punish a user in one of several methods.  For naughty users.  Syntax: punish @user"
				when "/newsongs"
					resp = "find new songs by checking out one of 40+ dubstep channels that post new music daily"
				when "/whywoot"
					resp = "DJ all day without throwing your life away clicking woot every 3 minutes.  Learn how and get the necessary tools"
				when "/theme"
					resp = "Learn what genres of music are generally accepted here.  Don't forget to check if your song is in /overplayed though"
				when "/rules"
					resp = "Room rules.  Duh"
				when "/roomhelp"
					resp = "Information about the room for the newer folk."
				when "/source"
					resp = "About the bot and the code that produced it"
				when "/sourcecode"
					resp = "About the bot and the code that produced it"
				when "/author"
					resp = "About the bot and the code that produced it"
				when "/woot"
					resp = "Remind users to hit woot so they don't get removed.  either type /woot or /woot @user"
				when ".128"
					resp = "Mod only command. Flags songs that are bad quality."
				when "/tableflip"
					resp = "... flips a table"
				when "/tablefix"
					resp = "... fixes a table"
				when "/download"
					resp = "Provides a link to find downloads of mp3 of current song"
				when "/smokesesh"
					resp = "For when ya just wanna get high"
				when "/smoke"
					resp = "doobies"
				when "/dab"
					resp = "WOLVES uses this"
				when "/afks"
					resp = "List current DJs on deck that haven't chatted or voted in 5+ minutes"
				when "/allafks"
					resp = "List all users in room that haven't chatted or voted in 10+ minutes"
				when "/status"
					resp = "Uptime and total song stats"
				when "/unhook events all"
					resp = "Host only command.  It's complicated"
				when "/die"
					resp = "Host only command. Makes bot go bye bye"
				when "/reload"
					resp = "Host only command. Reload pup's script"
				when "/lock"
					resp = "Mod only command. Locks booth"
				when "/unlock"
					resp = "Mod only command. Unlocks booth"
				when "/overplayed"
					resp = "Links users to our overplayed song list"
				when "/whymeh"
					resp = "Explains to users why they should be mehing every song"
				when "/skip"
					resp = "Mod only command.  Skips song.  Works for skipping invisible DJs."
				when "/commands"
					resp = "Lists all commands.  Will only list commands available to caller's user class (user, mod, or host)"
				when "/resetafk"
					resp = "Mod only command.  Resets AFK timer for user.  Syntax: /resetafk @USER"
				when "/forceskip"
					resp = "Host only command.  Make pup skip songs when they are supposed to end (addresses triangles of death issue). Syntax: /forceskip [enable|disable]"
				when "/fb"
					resp = "Links to Dubstep Den's facebook page"
				when "/uservoice"
					resp = "Links to Dubstep Den's uservoice page"
				when "/dclookup"
					resp = "Mod only command.  Looks up user for a log of their last disconnect. Syntax: /dclookup @USER"
				when "/reminder"
					resp = "Mod only command.  Set reminder for x songs from now.  For users that dc'd mainly.  Syntax: /reminder \"MSG\" [numsongs]"
				when "/voteratio"
					resp = "Mod only command.  See woot & meh count for user since bot launch.  Syntax: /voteratio @USER"
				when "/avgvoteratio"
					resp = "Mod only command.  See average voting ratio of every present user in room. Syntax: /avgvoteratio"
				when "/cmdhelp"
					resp = "Looks like you got it down"
				when "/pop"
					resp = "Mod only command.  Removes last person on deck"
				when "/push"
					resp = "Mod only command.  Puts user on deck. Syntax: /push @user"
				else
					resp = "That is nothing.  That is not a thing."
		else # none
			resp = "Use this command to learn how use other commands.  Syntax: /cmdhelp [/CMD]"

		API.sendChat resp
		
