// Generated by CoffeeScript 1.3.3
var afkCheck, msToStr;

afkCheck = function() {
  var DJs, id, lastActivity, lastWarned, now, oneMinute, secsLastActive, timeSinceLastActivity, timeSinceLastWarning, twoMinutes, user, warnMsg, _ref, _results;
  _ref = data.users;
  _results = [];
  for (id in _ref) {
    user = _ref[id];
    now = new Date();
    lastActivity = user.getLastActivity();
    timeSinceLastActivity = now.getTime() - lastActivity.getTime();
    if (timeSinceLastActivity > data.afkTime) {
      if (user.getIsDj()) {
        secsLastActive = timeSinceLastActivity / 1000;
        if (user.getWarningCount() === 0) {
          user.warn();
          _results.push("@" + user.getUser().username + ", I haven't seen you chat or vote in at least 12 minutes. Are you AFK?  If you don't show activity in 2 minutes I will remove you.");
        } else if (user.getWarningCount() === 1) {
          lastWarned = user.getLastWarning();
          timeSinceLastWarning = now.getTime() - lastWarned.getTime();
          twoMinutes = 2 * 60 * 1000;
          if (timeSinceLastWarning > twoMinutes) {
            user.warn();
            warnMsg = "@" + user.getUser().username;
            warnMsg += ", I haven't seen you chat or vote in at least 14 minutes now.  This is your second and FINAL warning.  If you do not chat or vote in the next minute I will remove you.";
            _results.push(warnMsg);
          } else {
            _results.push(void 0);
          }
        } else if (user.getWarningCount() === 2) {
          lastWarned = user.getLastWarning();
          timeSinceLastWarning = now.getTime() - lastWarned.getTime();
          oneMinute = 1 * 60 * 1000;
          if (timeSinceLastWarning > oneMinute) {
            DJs = API.getDJs();
            if (DJs.length > 0 && DJs[0].id !== user.getUser().id) {
              "@" + user.getUser().username + ", you had 2 warnings. Please stay active by chatting or voting.";
              _results.push(user.warn());
            } else {
              _results.push(void 0);
            }
          } else {
            _results.push(void 0);
          }
        } else {
          _results.push(void 0);
        }
      } else {
        _results.push(user.notDj());
      }
    } else {
      _results.push(void 0);
    }
  }
  return _results;
};

msToStr = function(msTime) {
  var ms, msg, timeAway;
  msg = '';
  timeAway = {
    'days': 0,
    'hours': 0,
    'minutes': 0,
    'seconds': 0
  };
  ms = {
    'day': 24 * 60 * 60 * 1000,
    'hour': 60 * 60 * 1000,
    'minute': 60 * 1000,
    'second': 1000
  };
  if (msTime > ms['day']) {
    timeAway['days'] = Math.floor(msTime / ms['day']);
    msTime = msTime % ms['day'];
  }
  if (msTime > ms['hour']) {
    timeAway['hours'] = Math.floor(msTime / ms['hour']);
    msTime = msTime % ms['hour'];
  }
  if (msTime > ms['minute']) {
    timeAway['minutes'] = Math.floor(msTime / ms['minute']);
    msTime = msTime % ms['minute'];
  }
  if (msTime > ms['second']) {
    timeAway['seconds'] = Math.floor(msTime / ms['second']);
  }
  if (timeAway['days'] !== 0) {
    msg += timeAway['days'].toString() + 'd';
  }
  if (timeAway['hours'] !== 0) {
    msg += timeAway['hours'].toString() + 'h';
  }
  if (timeAway['minutes'] !== 0) {
    msg += timeAway['minutes'].toString() + 'm';
  }
  if (timeAway['seconds'] !== 0) {
    msg += timeAway['seconds'].toString() + 's';
  }
  if (msg !== '') {
    return msg;
  } else {
    return false;
  }
};
