// Generated by CoffeeScript 1.3.3

({
  lockBooth: function() {
    return $.ajax({
      url: "http://www.plug.dj/gateway/room.update_options",
      type: 'POST',
      data: JSON.stringify({
        service: "room.update_options",
        body: [
          "dubstep-den", {
            "boothLocked": true,
            "waitListEnabled": true,
            "maxPlays": 1,
            "maxDJs": 5
          }
        ]
      }),
      async: this.async,
      dataType: 'json',
      contentType: 'application/json'
    });
  },
  unlockBooth: function() {
    return $.ajax({
      url: "http://www.plug.dj/gateway/room.update_options",
      type: 'POST',
      data: JSON.stringify({
        service: "room.update_options",
        body: [
          "dubstep-den", {
            "boothLocked": false,
            "waitListEnabled": true,
            "maxPlays": 1,
            "maxDJs": 5
          }
        ]
      }),
      async: this.async,
      dataType: 'json',
      contentType: 'application/json'
    });
  }
});
