// Generated by CoffeeScript 1.3.3
var apiHooks, hook, initHooks, undoHooks, unhook;

hook = function(apiEvent, callback) {
  return API.addEventListener(apiEvent, callback);
};

unhook = function(apiEvent, callback) {
  return API.removeEventListener(apiEvent, callback);
};

apiHooks = [
  {
    'event': API.ROOM_SCORE_UPDATE,
    'callback': updateVotes
  }, {
    'event': API.CURATE_UPDATE,
    'callback': announceCurate
  }, {
    'event': API.DJ_UPDATE,
    'callback': updateDjs
  }, {
    'event': API.USER_JOIN,
    'callback': handleUserJoin
  }, {
    'event': API.DJ_ADVANCE,
    'callback': handleNewSong
  }, {
    'event': API.VOTE_UPDATE,
    'callback': handleVote
  }, {
    'event': API.CHAT,
    'callback': chatCommandDispatcher
  }, {
    'event': API.USER_LEAVE,
    'callback': handleUserLeave
  }
];

initHooks = function() {
  var pair, _i, _len, _results;
  _results = [];
  for (_i = 0, _len = apiHooks.length; _i < _len; _i++) {
    pair = apiHooks[_i];
    _results.push(hook(pair['event'], pair['callback']));
  }
  return _results;
};

undoHooks = function() {
  var pair, _i, _len, _results;
  _results = [];
  for (_i = 0, _len = apiHooks.length; _i < _len; _i++) {
    pair = apiHooks[_i];
    _results.push(unhook(pair['event'], pair['callback']));
  }
  return _results;
};
