// Generated by CoffeeScript 1.3.3
var RoomHelper;

RoomHelper = (function() {

  function RoomHelper() {}

  RoomHelper.prototype.lookupUser = function(username) {
    var id, u, _ref;
    _ref = data.users;
    for (id in _ref) {
      u = _ref[id];
      if (u.getUser().username === username) {
        return u.getUser();
      }
    }
    return false;
  };

  RoomHelper.prototype.userVoteRatio = function(user) {
    var songId, songVotes, vote, votes;
    console.log("vote log pull for " + user.username + ":", data.voteLog[user.id]);
    songVotes = data.voteLog[user.id];
    votes = {
      'woot': 0,
      'meh': 0
    };
    for (songId in songVotes) {
      vote = songVotes[songId];
      if (vote === 1) {
        votes['woot']++;
      } else if (vote === -1) {
        votes['meh']++;
      }
    }
    votes['positiveRatio'] = (votes['woot'] / (votes['woot'] + votes['meh'])).toFixed(2);
    return votes;
  };

  return RoomHelper;

})();
