// Generated by CoffeeScript 1.3.3
var RoomHelper;

RoomHelper = (function() {

  function RoomHelper() {}

  RoomHelper.prototype.lookupUser = function(username) {
    var u, _i, _len, _ref;
    _ref = data.users;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      u = _ref[_i];
      if (u.getUser().username === u) {
        return u.getUser();
      }
    }
    return false;
  };

  return RoomHelper;

})();
