// Generated by CoffeeScript 1.3.3
var allAfksCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

allAfksCommand = (function(_super) {

  __extends(allAfksCommand, _super);

  function allAfksCommand() {
    return allAfksCommand.__super__.constructor.apply(this, arguments);
  }

  allAfksCommand.prototype.init = function() {
    this.command = '/allafks';
    this.parseType = 'exact';
    return this.rankPrivelege = 'user';
  };

  allAfksCommand.prototype.functionality = function() {
    var msg, now, u, uAfk, usrs, _i, _len;
    msg = '';
    usrs = API.getUsers();
    for (_i = 0, _len = usrs.length; _i < _len; _i++) {
      u = usrs[_i];
      now = new Date();
      uAfk = now.getTime() - data.users[u.id].getLastActivity().getTime();
      if (uAfk > (10 * 60 * 1000)) {
        if (msToStr(uAfk) !== false) {
          msg += u.username + ' - ' + msToStr(uAfk);
          msg += '. ';
        }
      }
    }
    if (msg === '') {
      return API.sendChat("No one is AFK");
    } else {
      return API.sendChat('AFKs: ' + msg);
    }
  };

  return allAfksCommand;

})(Command);
