// Generated by CoffeeScript 1.3.3
var badQualityCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

badQualityCommand = (function(_super) {

  __extends(badQualityCommand, _super);

  function badQualityCommand() {
    return badQualityCommand.__super__.constructor.apply(this, arguments);
  }

  badQualityCommand.prototype.init = function() {
    this.command = '.128';
    this.parseType = 'exact';
    return this.rankPrivelege = 'mod';
  };

  badQualityCommand.prototype.functionality = function() {
    var msg;
    msg = "Flagged for bad sound quality. Where do you get your music? The garbage can? Don't play this low quality tune again!";
    return API.sendChat(msg);
  };

  return badQualityCommand;

})(Command);
