// Generated by CoffeeScript 1.3.3
var Command;

Command = (function() {

  function Command(msgData) {
    this.msgData = msgData;
  }

  Command.prototype.parseType = null;

  Command.prototype.command = null;

  Command.prototype.rankPrivelege = null;

  Command.prototype.functionality = function(data) {};

  Command.prototype.getParseType = function() {
    return parseType;
  };

  Command.prototype.getCommand = function() {
    return command;
  };

  Command.prototype.getRankPrivelege = function() {
    return rankPrivelege;
  };

  return Command;

})();
