// Generated by CoffeeScript 1.3.3
var downloadCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

downloadCommand = (function(_super) {

  __extends(downloadCommand, _super);

  function downloadCommand() {
    return downloadCommand.__super__.constructor.apply(this, arguments);
  }

  downloadCommand.prototype.init = function() {
    this.command = '/download';
    this.parseType = 'exact';
    return this.rankPrivelege = 'user';
  };

  downloadCommand.prototype.functionality = function() {
    var e, eAuthor, eTitle, msg;
    e = encodeURIComponent;
    eAuthor = e(data.currentsong.author);
    eTitle = e(data.currentsong.title);
    msg = "Try this link for HIGH QUALITY DOWNLOAD: http://google.com/#hl=en&q=";
    msg += eAuthor + "%20-%20" + eTitle;
    msg += "%20site%3Azippyshare.com%20OR%20site%3Asoundowl.com%20OR%20site%3Ahulkshare.com%20OR%20site%3Asoundcloud.com";
    return API.sendChat(msg);
  };

  return downloadCommand;

})(Command);
