// Generated by CoffeeScript 1.3.3
var fbCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

fbCommand = (function(_super) {

  __extends(fbCommand, _super);

  function fbCommand() {
    return fbCommand.__super__.constructor.apply(this, arguments);
  }

  fbCommand.prototype.init = function() {
    this.command = '/fb';
    this.parseType = 'exact';
    return this.rankPrivelege = 'user';
  };

  fbCommand.prototype.functionality = function() {
    var m, msg;
    m = Math.floor(Math.random() * this.msgs.length);
    msg = this.msgs[m].replace('{fb}', 'http://www.facebook.com/1ND1EPLUS');
    return API.sendChat(msg);
  };

  fbCommand.prototype.msgs = ["Don't have any friends in real life? That's ok, we'll be your friend.  Join our facebook group: {fb}", "Wondering what a d a m looks like?  Join our facebook group ({fb}) and find out for yourself!", "We have a facebook group. Join it. Please. {fb}", "INDIE+ is now on friendster! lol just kidding.  Here's our facebook page: {fb} you should join.", "I bet you're handsome.  Join our facebook group so Nora can stalk your photos: {fb}"];

  return fbCommand;

})(Command);
