// Generated by CoffeeScript 1.3.3
var hugCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

hugCommand = (function(_super) {

  __extends(hugCommand, _super);

  function hugCommand() {
    return hugCommand.__super__.constructor.apply(this, arguments);
  }

  hugCommand.prototype.init = function() {
    this.command = 'hugs pup';
    this.parseType = 'exact';
    return this.rankPrivelege = 'user';
  };

  hugCommand.prototype.functionality = function() {
    return API.sendChat("hugs @" + this.msgData['from']);
  };

  return hugCommand;

})(Command);
