// Generated by CoffeeScript 1.3.3
var whyMehCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

whyMehCommand = (function(_super) {

  __extends(whyMehCommand, _super);

  function whyMehCommand() {
    return whyMehCommand.__super__.constructor.apply(this, arguments);
  }

  whyMehCommand.prototype.init = function() {
    this.command = '/whymeh';
    this.parseType = 'exact';
    return this.rankPrivelege = 'user';
  };

  whyMehCommand.prototype.functionality = function() {
    var msg;
    msg = "Reserve Mehs for songs that are a) extremely overplayed b) off genre c) absolutely god awful or d) troll songs. ";
    msg += "If you simply aren't feeling a song, then remain neutral";
    return API.sendChat(msg);
  };

  return whyMehCommand;

})(Command);
