// Generated by CoffeeScript 1.3.3
var overplayedCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

overplayedCommand = (function(_super) {

  __extends(overplayedCommand, _super);

  function overplayedCommand() {
    return overplayedCommand.__super__.constructor.apply(this, arguments);
  }

  overplayedCommand.prototype.init = function() {
    this.command = '';
    this.parseType = 'exact';
    return this.rankPrivelege = 'user';
  };

  overplayedCommand.prototype.functionality = function() {
    return API.sendChat("View the list of songs we consider overplayed and suggest additions at http://den.johnback.us/overplayed_tracks");
  };

  return overplayedCommand;

})(Command);
