// Generated by CoffeeScript 1.3.3
var protectCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

protectCommand = (function(_super) {

  __extends(protectCommand, _super);

  function protectCommand() {
    return protectCommand.__super__.constructor.apply(this, arguments);
  }

  protectCommand.prototype.init = function() {
    this.command = '/protect';
    this.parseType = 'startsWith';
    return this.rankPrivelege = 'mod';
  };

  protectCommand.prototype.functionality = function() {
    var id, msg, user, username, _ref;
    msg = this.msgData.message;
    if (msg.length > 9) {
      username = msg.substring(10);
      _ref = data.users;
      for (id in _ref) {
        user = _ref[id];
        if (user.getUser().username === username) {
          user["protected"] = true;
          API.sendChat("I shall protect you @" + username + " (I just wont kick you)");
          return;
        }
      }
    }
    API.sendChat("That aint no name I ever did see");
  };

  return protectCommand;

})(Command);
