// Generated by CoffeeScript 1.3.3
var pushCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

pushCommand = (function(_super) {

  __extends(pushCommand, _super);

  function pushCommand() {
    return pushCommand.__super__.constructor.apply(this, arguments);
  }

  pushCommand.prototype.init = function() {
    this.command = '/push';
    this.parseType = 'startsWith';
    return this.rankPrivelege = 'mod';
  };

  pushCommand.prototype.functionality = function() {
    var msg, name, r, user;
    msg = this.msgData.message;
    if (msg.length > this.command.length + 2) {
      name = msg.substr(this.command.length + 2);
      r = new RoomHelper();
      user = r.lookupUser(name);
      if (user !== false) {
        API.moderateAddDJ(user.id);
        return console.log("Adding User to DJ booth", user);
      } else {
        return console.log("could not find user with name " + name);
      }
    }
  };

  return pushCommand;

})(Command);
