// Generated by CoffeeScript 1.3.3
var rapeCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

rapeCommand = (function(_super) {

  __extends(rapeCommand, _super);

  function rapeCommand() {
    return rapeCommand.__super__.constructor.apply(this, arguments);
  }

  rapeCommand.prototype.init = function() {
    this.command = 'rapes pup';
    this.parseType = 'exact';
    return this.rankPrivelege = 'user';
  };

  rapeCommand.prototype.functionality = function() {
    return API.sendChat("slaps @" + this.msgData['from']);
  };

  return rapeCommand;

})(Command);
