// Generated by CoffeeScript 1.3.3
var releaseHoundsCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

releaseHoundsCommand = (function(_super) {

  __extends(releaseHoundsCommand, _super);

  function releaseHoundsCommand() {
    return releaseHoundsCommand.__super__.constructor.apply(this, arguments);
  }

  releaseHoundsCommand.prototype.init = function() {
    this.command = 'release the hounds';
    this.parseType = 'exact';
    return this.rankPrivelege = 'mod';
  };

  releaseHoundsCommand.prototype.functionality = function() {
    var afkmin, afksec, afktimout, dj, djtimeout, i;
    for (i in data.djs) {
      dj = data.djs[i].id;
    }
    djtimeout = data.afk[dj];
    if (isAfk(dj, djtimeout, 8)) {
      afktimout = (Date.now() - data.afk[dj]) / 60000;
    }
    afktimout = afktimout.toString().split(".");
    afkmin = afktimout[0];
    afksec = "." + afktimout[1];
    afksec = afksec * 60;
    API.sendChat("WOOF WOOF WOOF");
    API.sendChat("@" + data.djs[i].username + "'s not here. " + data.djs[i].username + " went away. " + data.djs[i].username + "'s gone. (Please chat or vote) AFK: " + afkmin + " min " + afksec.toFixed(0) + " sec.");
    return API.moderateRemoveDJ(djs[i].id);
  };

  return releaseHoundsCommand;

})(Command);
