// Generated by CoffeeScript 1.3.3
var reloadCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

reloadCommand = (function(_super) {

  __extends(reloadCommand, _super);

  function reloadCommand() {
    return reloadCommand.__super__.constructor.apply(this, arguments);
  }

  reloadCommand.prototype.init = function() {
    this.command = '/reload';
    this.parseType = 'exact';
    return this.rankPrivelege = 'host';
  };

  reloadCommand.prototype.functionality = function() {
    var pupSrc;
    API.sendChat('brb');
    undoHooks();
    pupSrc = data.pupScriptUrl;
    data.implode();
    return $.getScript(pupSrc);
  };

  return reloadCommand;

})(Command);
