// Generated by CoffeeScript 1.3.3
var resetAfkCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

resetAfkCommand = (function(_super) {

  __extends(resetAfkCommand, _super);

  function resetAfkCommand() {
    return resetAfkCommand.__super__.constructor.apply(this, arguments);
  }

  resetAfkCommand.prototype.init = function() {
    this.command = '/resetafk';
    this.parseType = 'startsWith';
    return this.rankPrivelege = 'mod';
  };

  resetAfkCommand.prototype.functionality = function() {
    var id, name, u, _ref;
    if (this.msgData.message.length > 10) {
      name = this.msgData.message.substring(11);
      _ref = data.users;
      for (id in _ref) {
        u = _ref[id];
        if (u.getUser().username === name) {
          u.updateActivity();
          API.sendChat('@' + u.getUser().username + '\'s AFK time has been reset.');
          return;
        }
      }
      API.sendChat('Not sure who ' + name + ' is');
    } else {
      API.sendChat('Yo Gimme a name r-tard');
    }
  };

  return resetAfkCommand;

})(Command);
