// Generated by CoffeeScript 1.3.3
var rulesCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

rulesCommand = (function(_super) {

  __extends(rulesCommand, _super);

  function rulesCommand() {
    return rulesCommand.__super__.constructor.apply(this, arguments);
  }

  rulesCommand.prototype.init = function() {
    this.command = '/rules';
    this.parseType = 'startsWith';
    return this.rankPrivelege = 'user';
  };

  rulesCommand.prototype.functionality = function() {
    var msg;
    msg = "1) Play good sound quality music. ";
    msg += "2) Don't replay a song on the room history. 3) Max song limit 8 minutes. ";
    msg += "4) DO NOT GO AWAY FROM KEYBOARD ON DECK! Please WOOT on DJ Booth and respect your fellow DJs!";
    return API.sendChat(msg);
  };

  return rulesCommand;

})(Command);
