// Generated by CoffeeScript 1.3.3
var smokeCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

smokeCommand = (function(_super) {

  __extends(smokeCommand, _super);

  function smokeCommand() {
    return smokeCommand.__super__.constructor.apply(this, arguments);
  }

  smokeCommand.prototype.init = function() {
    this.command = ['/smokesesh', '/smoke', '/dab'];
    this.parseType = 'exact';
    return this.rankPrivelege = 'user';
  };

  smokeCommand.prototype.smoke = function() {
    var r;
    r = Math.floor(Math.random() * this.responses.length);
    return this.responses[r];
  };

  smokeCommand.prototype.functionality = function() {
    return API.sendChat(this.smoke());
  };

  smokeCommand.prototype.responses = ["If we all had a bong we'd all get along.", "/me rolls a joint for you.", "Got anything to eat?", "Y-y-you're crazy....", "THE COLORS. THE FUCKIN COLORS!", "Everyone needs to give me a hug.", "Need to blaze til' my eyes glaze."];

  return smokeCommand;

})(Command);
