// Generated by CoffeeScript 1.3.3
var sourceCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

sourceCommand = (function(_super) {

  __extends(sourceCommand, _super);

  function sourceCommand() {
    return sourceCommand.__super__.constructor.apply(this, arguments);
  }

  sourceCommand.prototype.init = function() {
    this.command = ['/source', '/sourcecode', '/author'];
    this.parseType = 'exact';
    return this.rankPrivelege = 'user';
  };

  sourceCommand.prototype.functionality = function() {
    var msg;
    msg = 'Backus wrote me in CoffeeScript.  A generalized version of me should be available on github soon!';
    return API.sendChat(msg);
  };

  return sourceCommand;

})(Command);
