// Generated by CoffeeScript 1.3.3
var statusCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

statusCommand = (function(_super) {

  __extends(statusCommand, _super);

  function statusCommand() {
    return statusCommand.__super__.constructor.apply(this, arguments);
  }

  statusCommand.prototype.init = function() {
    this.command = '/status';
    this.parseType = 'exact';
    return this.rankPrivelege = 'user';
  };

  statusCommand.prototype.functionality = function() {
    var day, hour, launch, lt, meridian, min, month, msg, t, totals;
    lt = data.launchTime;
    month = lt.getMonth() + 1;
    day = lt.getDate();
    hour = lt.getHours();
    meridian = hour % 12 === hour ? 'AM' : 'PM';
    min = lt.getMinutes();
    min = min < 10 ? '0' + min : min;
    t = data.totalVotingData;
    t['songs'] = data.songCount;
    launch = 'Initiated ' + month + '/' + day + ' ' + hour + ':' + min + ' ' + meridian + '. ';
    totals = '' + t.songs + ' songs have been played, accumulating ' + t.woots + ' woots, ' + t.mehs + ' mehs, and ' + t.curates + ' queues.';
    msg = launch + totals;
    return API.sendChat(msg);
  };

  return statusCommand;

})(Command);
