// Generated by CoffeeScript 1.3.3
var tableFixCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

tableFixCommand = (function(_super) {

  __extends(tableFixCommand, _super);

  function tableFixCommand() {
    return tableFixCommand.__super__.constructor.apply(this, arguments);
  }

  tableFixCommand.prototype.init = function() {
    this.command = '/tablefix';
    this.parseType = 'exact';
    return this.rankPrivelege = 'user';
  };

  tableFixCommand.prototype.functionality = function() {
    return API.sendChat(" ┬─┬ノ( º _ ºノ)");
  };

  return tableFixCommand;

})(Command);
