// Generated by CoffeeScript 1.3.3
var tacoCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

tacoCommand = (function(_super) {

  __extends(tacoCommand, _super);

  function tacoCommand() {
    return tacoCommand.__super__.constructor.apply(this, arguments);
  }

  tacoCommand.prototype.init = function() {
    this.command = 'pizza';
    this.parseType = 'startsWith';
    return this.rankPrivelege = 'user';
  };

  tacoCommand.prototype.randomTaco = function() {
    var t, tacos;
    tacos = ["cheese pizza", "pepperoni pizza", "hawaiian pizza", "BBQ chicken pizza", "anchovies pizza", "DNCH turkey pizza", "Adam's pepperoni pizza", "vegan pizza"];
    t = Math.floor(Math.random() * tacos.length);
    return tacos[t];
  };

  tacoCommand.prototype.functionality = function() {
    var msg, r, user;
    msg = this.msgData.message;
    r = new RoomHelper();
    if (msg.length > 8) {
      user = r.lookupUser(msg.substr(8));
      if (user === false) {
        API.sendChat("/em doesn't see '" + msg.substr(8) + "' in room and eats pizza himself");
        return false;
      } else {
        return API.sendChat("@" + user.username + ", @" + this.msgData.from + " has rewarded you with some " + this.randomTaco() + ".");
      }
    }
  };

  return tacoCommand;

})(Command);
