// Generated by CoffeeScript 1.3.3
var themeCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

themeCommand = (function(_super) {

  __extends(themeCommand, _super);

  function themeCommand() {
    return themeCommand.__super__.constructor.apply(this, arguments);
  }

  themeCommand.prototype.init = function() {
    this.command = '/theme';
    this.parseType = 'startsWith';
    return this.rankPrivelege = 'user';
  };

  themeCommand.prototype.functionality = function() {
    var msg;
    msg = "Any type of Bass Music is allowed here. Including Dubstep, Complextro, Drum and Bass, ";
    msg += "Garage, Breakbeat, Hardstyle, Moombahton, HEAVY EDM, House, Electro, and Trance!!";
    return API.sendChat(msg);
  };

  return themeCommand;

})(Command);
