// Generated by CoffeeScript 1.3.3
var whyWootCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

whyWootCommand = (function(_super) {

  __extends(whyWootCommand, _super);

  function whyWootCommand() {
    return whyWootCommand.__super__.constructor.apply(this, arguments);
  }

  whyWootCommand.prototype.init = function() {
    this.command = '/whywoot';
    this.parseType = 'startsWith';
    return this.rankPrivelege = 'user';
  };

  whyWootCommand.prototype.functionality = function() {
    var msg, nameIndex;
    msg = "We dislike AFK djs. We calculate your AFK status by checking the last time you			Woot'd or spoke. If you don't woot, I'll automagically remove you. Use our AutoWoot			script to avoid being removed: http://bit.ly/McZdWw";
    if ((nameIndex = this.msgData.message.indexOf('@')) !== -1) {
      return API.sendChat(this.msgData.message.substr(nameIndex) + ', ' + msg);
    } else {
      return API.sendChat(msg);
    }
  };

  return whyWootCommand;

})(Command);
